### ISSUE TITLE
Failed Claim

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [db0/fediseer#18] opened 2023-09-04 23:32 UTC
Original Ticket:

https://github.com/XtremeOwnageDotCom/FediseerGui/issues/19

Posted by [tmajibon](https://github.com/tmajibon)

**Comment by db0** [comment] 2023-09-05 08:45
@tmajibon I just initiated an api key reset for user `shiri` which I assume it you. Can you check if it went through now? If not, it's possible that your instance is dropping it connections from fediseer, for example because you're using an allow-list. Can you tell me if you do?

**Comment by tmajibon** [comment] 2023-09-05 13:31
Yes that's me and no message received, no allow-list either.

Might I suggest a change in process btw for key reset, I'd suggest creating temporary reset keys on a reset call which can optionally be passed to claim for when a key is already set. It would help with normal instances of lost keys, but prevent hijacking.

**Comment by db0** [comment] 2023-09-05 14:29
The problem with this approach is how to know you're resetting the keys for the right person, you know?

I've added now a way to reset the key and get the result on the response. Lemme see if I can message you through lemmy so I can reset the key on my end. Then you'll be able to use the key I send you to reset the API so that only you have it.

I'm also curious if you can check if your friendica instance is dropping the fediseer messages. I tested this with a temp friendica account and I work for me, so I know it's not the software communication.

**Comment by db0** [comment] 2023-09-05 14:30
I just sent you a PM from lemmy.

**Comment by tmajibon** [comment] 2023-09-05 14:37
Not received... apparently there's a setting for unsolicited messages in Friendica that I didn't notice before. Flipped it and I suspect it might work now.

And now I'm confused about how someone a week ago sent me an unsolicited message successfully...

From the GUI app I knew that there were friendica nodes, which made this especially confusing.

**Comment by db0** [comment] 2023-09-05 14:50
Sent another PM from lemmy.

**Comment by db0** [comment] 2023-09-05 15:16
Indeed. So something seems funky on your friendica. Did you get my PM from mastodon just now?

**Comment by db0** [comment] 2023-09-05 15:17
also, can you try to PM me on lemmy? @db0@lemmy.dbzer0.com

**Comment by tmajibon** [comment] 2023-09-05 15:23
We confirmed that message from mastodon works fine, but not lemmy.

I'll note that there's well established issues between Lemmy and Friendica, they only *kinda* work together (the big one I see all the time is that Lemmy doesn't propagate the comments over to Friendica on posts, so I can't see any comments without going to the original page, or searching that comment... which will give me just that comment and any comment it was replying to)

**Comment by db0** [comment] 2023-09-05 15:44
Ye, lemmy doesn't work all that well with mastodon either. We can put the problem about the lemmy PMs down to that. Did you perhaps receive a PM about your new guarantee ?

**Comment by tmajibon** [comment] 2023-09-05 17:43
I've received no PMs from the system at all.

**Comment by db0** [comment] 2023-09-05 20:10
OK. I don't know what is the problem with talking to your instance. But now you have access to the API, so I'm closing this

**Closed by db0** 2023-09-05 20:10 UTC
